spring.application.name=BingeVerse
spring.data.mongodb.uri=mongodb+srv://BingeVerse:MovieApp%40123@bingeverse.2hzjsq0.mongodb.net/?retryWrites=true&w=majority&appName=BingeVerse
spring.data.mongodb.database=BingeVerseDB
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

server.port=8080

# Optional CORS (temporary)
spring.mvc.cors.allowed-origins=*
